apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony
  template:
    metadata:
      labels:
        app: symfony
    spec:
      containers:
      - name: symfony
        image: ""
        imagePullPolicy: Always
        env:
        - name: MY_IMAGE
          valueFrom:
            secretKeyRef:
              name: my-image-secret
              key: image
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: symfony
spec:
  selector:
    app: symfony
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
